# Site
title: 'ThoughtWorks - Auras'

# URL
url: ''
baseurl: '/sus2018-proto-app'
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 8200

# Data
social:
  facebook_user: "facebook.user"
  twitter_user: "twitteruser"
